tasks:
  - name: SDK
    before: |
      npm install -g aws-cdk
# https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
  - name: teraform
    before: |
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt update
      sudo apt-get install terraform  
  # random utilities
  - name: utils
    before: |
      sudo apt-get install tree
  # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
  # https://docs.aws.amazon.com/powershell/latest/userguide/pstools-welcome.html
  - name: PowerShell
    before: |
      sudo apt-get update
      sudo apt-get install -y wget apt-transport-https software-properties-common
      wget -q "https://packages.microsoft.com/keys/microsoft.asc" -O- | sudo apt-key add -
      sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/prod.list)"
      sudo apt-get update
      sudo apt-get install -y powershell
  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#:~:text=Install%20or%20update%20the%20%20AWS%20CLI%201,--version%20command.%20C%3A%5C%3E%20%20aws%20--version%20%20
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-portial
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    before: |
      cd /workspace 
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      cd $THEIA_WORKSPACE_ROOT
