#!/usr/bin/env bash
echo "== deploy s3 bucket via CFN"

STACNK_NAME="cnd-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--region eu-central-1 \
--stack-name $STACNK_NAME \
--no-execute-changeset
